version: '3.8'

networks:
  monitoring:
    driver: bridge
    
volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  node-exporter:
    container_name: node_exporter
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/server_alerts.yml:/etc/prometheus/server_alerts.yml
      - ./prometheus/cosmos_alerts.yml:/etc/prometheus/cosmos_alerts.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring

  alertmanager:
    container_name: alert_manager
    image: prom/alertmanager:latest
    restart: unless-stopped
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    expose:
      - 9093
    networks:
      - monitoring

  alertmanager-bot:
    container_name: alert_manager_bot
    image: metalmatze/alertmanager-bot:latest
    restart: unless-stopped
    environment:
      - ALERTMANAGER_URL=http://alert_manager:9093
      - LISTEN_ADDR=0.0.0.0:8080
      - BOLT_PATH=/data/bot.db
      - STORE=bolt
      - TELEGRAM_ADMIN=1111111              # your telegram user id
      - TELEGRAM_TOKEN=11111111:AAG_XXXXXXX # your telegram bot token
      - TEMPLATE_PATHS=/templates/default.tmpl
    volumes:
      - ./alertmanager-bot:/data
    expose:
      - 8080
    networks:
      - monitoring

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
#    environment:
#      - GF_SERVER_PROTOCOL=https
#      - GF_SERVER_CERT_FILE=/etc/grafana/ssl/grafana.crt
#      - GF_SERVER_CERT_KEY=/etc/grafana/ssl/grafana.key
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/ssl:/etc/grafana/ssl
    ports:
      - 80:3000
    networks:
      - monitoring
    depends_on:
      - prometheus
