groups:
- name: Cosmos Alerts  
  rules:

  - alert: ValidatorMissingBlocks
    expr: rate(tendermint_consensus_validator_missed_blocks[1m]) != 0
    for: 1m
    labels:
      severity: major
    annotations:
      description: "Missing Blocks"

  - alert: ValidatorDegradedSyncing
    expr: increase(tendermint_consensus_latest_block_height[5m]) < 40
    for: 5m
    labels:
      severity: major
    annotations:
      description: "Degraded syncing performance"

  - alert: ValidatorTooFewPeers
    expr: tendermint_p2p_peers < 5
    for: 5m
    labels:
      severity: major
    annotations:
      description: "Number of peers (P2P) is lower than threshold (5)"
