groups:
- name: Cosmos Alerts  
  rules:

  - alert: ValidatorMissingBlocks
    expr: rate(tendermint_consensus_validator_missed_blocks[5m]) > 10
    for: 1m
    labels:
      severity: major
    annotations:
      description: "Validator missing blocks (>=10 in last 5 minutes)"

  - alert: ValidatorDegradedSyncing
    expr: increase(tendermint_consensus_latest_block_height{skip_sync_alert!="true"}[10m]) < 20
    for: 10m
    labels:
      severity: major
    annotations:
      description: "Degraded syncing performance (less than 20 blocks in the last 10 min)"

  - alert: ValidatorTooFewPeers
    expr: tendermint_p2p_peers < 3
    for: 5m
    labels:
      severity: major
    annotations:
      description: "Number of peers is lower than threshold (<3)"
