groups:
- name: Cosmos Alerts  
  rules:

  - alert: ValidatorMissingBlocks
    expr: rate(tendermint_consensus_validator_missed_blocks[1m]) != 0
    for: 1m
    labels:
      severity: major
    annotations:
      description: "Validator missing blocks (&gt;=1 in last minute)"

  - alert: ValidatorDegradedSyncing
    expr: increase(tendermint_consensus_latest_block_height[5m]) < 40
    for: 5m
    labels:
      severity: major
    annotations:
      description: "Degraded syncing performance (less than 40 blocks in the last 5 min)"

  - alert: ValidatorTooFewPeers
    expr: tendermint_p2p_peers < 5
    for: 5m
    labels:
      severity: major
    annotations:
      description: "Number of peers is lower than threshold (&lt;5)"
