groups:
- name: Cosmos Alerts  
  rules:

  - alert: ValidatorMissingBlocks
    expr: rate(tendermint_consensus_validator_missed_blocks[1m]) != 0
    for: 1m
    labels:
      severity: major
    annotations:
      summary: "Missing Blocks"
      description: "{{ $labels.instance }} missed some blocks"

  - alert: ValidatorDegradedSyncing
    expr: increase(tendermint_consensus_latest_block_height[5m]) < 40
    for: 5m
    labels:
      severity: major
    annotations:
      summary: "Degraded syncing performance"
      description: "Degraded syncing performance - Instance {{ $labels.label }}; host: {{ $labels.instance }}"

  - alert: ValidatorTooFewPeers
    expr: tendermint_p2p_peers < 5
    for: 5m
    labels:
      severity: major
    annotations:
      summary: "Low number of peers"
      description: 'P2P Peers on {{ $labels.label }}; host: {{ $labels.instance }} is lower than threshold (5)'
